#!/usr/bin/env sh
python3 ../scripts/ucode/microcode_gen.py
cd ../asm
for file in `ls`
do
    lc3as $file > tmp
    ../scripts/binmgmt/lc3obj2memh.py *.obj
    cp *.hex ../run
    ls | grep -Ev "asm" | xargs rm
done
cd ../run
iverilog ../rtl/lc3_*
# echo "Starting sim"
# ./a.out | sed -n '2,/*/p'
./a.out
ls | grep -Ev "run\_lc3" | xargs rm
